wip welp go for shell after all
This is copied from zulip-mobile's tools/test,
but with the list of suites replaced, and most of the features
(notably --diff and its friends) stripped out.

Also it uses `set -u` and `set -o pipefail`.

diff --git a/tools/check b/tools/check
--- a/tools/check
+++ b/tools/check
@@ -1,3 +1,88 @@
 #!/usr/bin/env bash
+
+# Careful! `set -e` doesn't do everything you'd think it does. In
+# fact, we don't get its benefit in any of the `run_foo` functions.
+#
+# This is because it has an effect only when it can exit the whole shell.
+# (Its full name is `set -o errexit`, and it means "exit" literally.)  See:
+#   https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
+#
+# When one test suite fails, we want to go on to run the other suites, so
+# we use `||` to prevent the whole script from exiting there, and that
+# defeats `set -e`.
+#
+# For now our workaround is to put `|| return` in the `run_foo` just
+# after each nontrivial command that isn't the final command in the
+# function.
+set -euo pipefail
+
 this_dir=${BASH_SOURCE[0]%/*}
-exec dart --enable-asserts "${this_dir}"/lib/check.dart "$@"
+
+## CLI PARSING
+
+default_suites=(analyze flutter_test)
+extra_suites=(
+)
+
+usage() {
+    cat >&2 <<EOF
+usage: tools/check [SUITE]...
+
+Run our tests.
+
+By default, run ${#default_suites[@]} suite(s):
+  ${default_suites[*]}
+and skip ${#extra_suites[@]} suite(s):
+  ${extra_suites[*]}
+EOF
+    exit 2
+}
+
+opt_suites=()
+while (( $# )); do
+    case "$1" in
+        analyze|flutter_test)
+            opt_suites+=("$1"); shift;;
+        *) usage;;
+    esac
+done
+
+if (( ! "${#opt_suites[@]}" )); then
+    opt_suites=( "${default_suites[@]}" )
+fi
+
+
+## EXECUTION
+
+rootdir=$(git rev-parse --show-toplevel)
+cd "$rootdir"
+
+run_analyze() {
+    flutter analyze
+}
+
+run_flutter_test() {
+    flutter test
+}
+
+failed=()
+for suite in "${opt_suites[@]}"; do
+    echo "Running $suite..."
+    case "$suite" in
+        analyze)      run_analyze ;;
+        flutter_test) run_flutter_test ;;
+    esac || failed+=($suite)
+done
+
+if [ -n "$failed" ]; then
+    cat >&2 <<EOF
+
+FAILED: ${failed[*]}
+
+To rerun the suites that failed, run:
+  $ tools/test ${failed[*]}
+EOF
+    exit 1
+fi
+
+echo "Passed!"
